#!/usr/bin/env python
# This script will capture information on a program that is run
# It can be used to capture information on a program that has not been instrumented,
# such as a program written by the user

import os
import sys
from umdinst.wrap import capture_interactive_run  

progname = sys.argv[1]
args = sys.argv[1:]

# Check if the program name is an absolute pathname
# or is in the local directory
if os.path.exists(progname):
    prog = progname
elif os.path.exists(os.path.join('.',progname)):
    prog = os.path.join('.',progname)
else:
    raise ValueError, "Can't find %s. Please specify path or run it from within the directory" % progname

success = capture_interactive_run(prog,argv=args)
if success:
    sys.exit(0)
else:
    sys.exit(1)


